REM   Script: Explicit Cursor
REM   Explicit Cursor

CREATE TABLE Workers( 
worker_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
name VARCHAR2(15), 
surname VARCHAR2(15), 
age int, 
salary int 
);

INSERT INTO Workers(name,surname,age,salary) Values ('Burak','Konuk','22','1500');

INSERT INTO Workers(name,surname,age,salary) Values ('Hatice','Kuru','23','1500');

DECLARE 
w_id Workers.worker_ID%type := 1; 
w_name Workers.name%type; 
w_surname Workers.surname%type; 
w_age Workers.age%type; 
w_salary Workers.salary%type; 
 
BEGIN 
Select name,surname,age,salary INTO w_name,w_surname,w_age,w_salary 
FROM Workers 
WHERE worker_ID = w_id; 
 
DBMS_output.put_line(w_id ||' ' ||  w_name || ' '  || w_surname || ' ' ||  w_age || ' ' || w_salary); 
 
END;
/

